---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: CheckReconfigured
    inherits: 
    description: 
    relative_path: Cloud/Orchestration/Reconfiguration/StateMachines/Methods/CheckReconfigured
  fields:
  - execute:
      value: check_reconfigured
