---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: reconfigure
    inherits: 
    description: reconfigure
    relative_path: Cloud/Orchestration/Reconfiguration/StateMachines/Methods/reconfigure
  fields:
  - execute:
      value: reconfigure
