---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
    relative_path: Infrastructure/VM/Retirement/StateMachines/VMRetirement/Default
  fields:
  - RemoveFromProvider:
      value: "/Infrastructure/VM/Retirement/StateMachines/Methods/RemoveFromProvider"
  - CheckRemovedFromProvider:
      value: "/Infrastructure/VM/Retirement/StateMachines/Methods/CheckRemovedFromProvider"
  - DeleteFromVMDB:
      value: "#/Infrastructure/VM/Retirement/StateMachines/Methods/DeleteFromVMDB"
