---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: CheckProvisioned
    inherits: 
    description: 
    relative_path: Infrastructure/Configured_System/Provisioning/StateMachines/Methods/CheckProvisioned
  fields:
  - execute:
      value: check_provisioned
