---
object_type: method
version: 1.0
object:
  attributes:
    name: reconfigure
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
    relative_path: Cloud/Orchestration/Reconfiguration/StateMachines/Methods/reconfigure
  inputs: []
