---
object_type: method
version: 1.0
object:
  attributes:
    name: vm_dialog_name_prefix
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
    relative_path: Infrastructure/VM/Provisioning/Profile/vm_dialog_name_prefix
  inputs: []
