---
object_type: method
version: 1.0
object:
  attributes:
    name: Host_Evacuation
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
    relative_path: Infrastructure/Host/Operations/Methods/Host_Evacuation
  inputs: []
