---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: default
    relative_path: Cloud/Orchestration/Reconfiguration/StateMachines/Reconfigure/default
  fields: []
