---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Clone VM to Template
    name: clone_to_template
    inherits: 
    description: 
    relative_path: Infrastructure/VM/Provisioning/StateMachines/VMProvision_Template/clone_to_template
  fields: []
