---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: PreProvision_Clone_to_VM
    inherits: 
    description: 
    relative_path: Infrastructure/VM/Provisioning/StateMachines/Methods/PreProvision_Clone_to_VM
  fields:
  - vmware_meth1:
      value: vmware_PreProvision_Clone_to_VM
  - redhat_meth1:
      value: redhat_PreProvision_Clone_to_VM
