---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Provision
    inherits: 
    description: 
    relative_path: Infrastructure/VM/Provisioning/StateMachines/Methods/Provision
  fields:
  - execute:
      value: provision
