---
object_type: method
version: 1.0
object:
  attributes:
    name: BestStorage
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
    relative_path: Infrastructure/VM/Migrate/StateMachines/Methods/BestStorage
  inputs: []
