---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: vm_reconfigure
    inherits: 
    description: 
    relative_path: System/Event/MiqEvent/POLICY/vm_reconfigure
  fields:
  - rel5:
      value: "/System/event_handlers/event_enforce_policy"
