---
object_type: method
version: 1.0
object:
  attributes:
    name: approve_request
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
    relative_path: Infrastructure/Configured_System/Provisioning/StateMachines/ProvisionRequestApproval/approve_request
  inputs: []
