---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: MiqProvisionConfiguredSystemRequest_approved
    inherits: 
    description: 
    relative_path: System/Policy/MiqProvisionConfiguredSystemRequest_approved
  fields:
  - rel5:
      value: "/System/Notification/Email/InfrastructureConfiguredSystemMiqProvisionRequestRequesterApproved"
  - rel6:
      value: "/System/Notification/Email/InfrastructureConfiguredSystemMiqProvisionRequestApproverApproved"
