---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: MiqProvisionConfiguredSystemRequest_denied
    inherits: 
    description: 
    relative_path: System/Policy/MiqProvisionConfiguredSystemRequest_denied
  fields:
  - rel5:
      value: "/System/Notification/Email/InfrastructureConfiguredSystemMiqProvisionRequestRequesterDenied"
  - rel6:
      value: "/System/Notification/Email/InfrastructureConfiguredSystemMiqProvisionRequestApproverDenied"
