---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: MiqProvisionConfiguredSystemRequest_starting
    inherits: 
    description: 
    relative_path: System/Policy/MiqProvisionConfiguredSystemRequest_starting
  fields:
  - rel5:
      value: "/System/CommonMethods/QuotaStatemachine/quota"
