---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: VmCloudReconfigureRequest_created
    inherits: 
    description: 
    relative_path: System/Policy/VmCloudReconfigureRequest_created
  fields:
  - meth5:
      value: vmcloudreconfigure_request_auto_approve
