---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: VmReconfigureRequest_starting
    inherits: 
    description: 
    relative_path: System/Policy/VmReconfigureRequest_starting
  fields:
  - rel2:
      value: "/System/CommonMethods/QuotaStatemachine/quota"
