---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: VmReconfigureRequest_approved
    inherits: 
    description: 
    relative_path: System/Policy/VmReconfigureRequest_approved
  fields:
  - rel5:
      value: "/System/Notification/Email/VmReconfigureRequestApproved"
