---
object_type: method
version: 1.0
object:
  attributes:
    name: Provision_Complete
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
    relative_path: Infrastructure/Configured_System/Provisioning/Email/Provision_Complete
  inputs: []
