---
object_type: method
version: 1.0
object:
  attributes:
    name: Request_Approved
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
    relative_path: Infrastructure/Configured_System/Provisioning/Email/Request_Approved
  inputs: []
