---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: 
    relative_path: System/Event/StateMachines/Refresh/default
  fields:
  - refresh:
      value: METHOD::target_refresh
  - check_refreshed:
      value: METHOD::check_refreshed
  - policy:
      value: "/System/event_handlers/event_action_policy?target=${#policy_target}&policy_event=${#policy_event}&param="
