---
object_type: method
version: 1.0
object:
  attributes:
    name: microsoft_best_fit_least_utilized
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
    relative_path: Infrastructure/VM/Provisioning/Placement/microsoft_best_fit_least_utilized
  inputs: []
