---
object_type: method
version: 1.0
object:
  attributes:
    name: redhat_best_placement_with_scope
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
    relative_path: Infrastructure/VM/Provisioning/Placement/redhat_best_placement_with_scope
  inputs: []
