---
object_type: method
version: 1.0
object:
  attributes:
    name: vmware_best_fit_with_scope
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
    relative_path: Infrastructure/VM/Provisioning/Placement/vmware_best_fit_with_scope
  inputs: []
