---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
    relative_path: Cloud/VM/Provisioning/StateMachines/ProvisionRequestApproval/Default
  fields:
  - max_vms:
      value: '1'
