---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: UI_Configured_System_Provision_Info
    inherits: 
    description: 
    relative_path: System/Request/UI_Configured_System_Provision_Info
  fields:
  - rel5:
      value: "/Infrastructure/Configured_System/Provisioning/Profile/${/#user.normalized_ldap_group}#${process#message}"
