---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Default
    name: Default
    inherits: 
    description: 
    relative_path: Infrastructure/Configured_System/Provisioning/StateMachines/ProvisionRequestApproval/Default
  fields: []
