---
object_type: method
version: 1.0
object:
  attributes:
    name: start_retirement
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
    relative_path: Infrastructure/VM/Retirement/StateMachines/Methods/start_retirement
  inputs: []
