---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: ConfigurationItemChangeNotification
    inherits: 
    description: 
    relative_path: System/Event/EmsEvent/Amazon/ConfigurationItemChangeNotification
  fields:
  - rel4:
      value: "/System/event_handlers/refresh"
