---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: service_reconfigure_finished
    inherits: 
    description: 
    relative_path: System/CommonMethods/StateMachineMethods/service_reconfigure_finished
  fields:
  - execute:
      value: task_finished(object => 'service_reconfigure_task', message => 'Service
        Reconfigured Successfully')
