---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: default
    relative_path: Service/Provisioning/StateMachines/ServiceProvision_Template/default
  fields: []
