---
object_type: method
version: 1.0
object:
  attributes:
    name: vmcloudreconfigure_request_auto_approve
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
    relative_path: System/Policy/vmcloudreconfigure_request_auto_approve
  inputs: []
