---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: CloudOrchestrationServiceReconfigureRequesterApproved
    inherits: 
    description: 
    relative_path: System/Notification/Email/CloudOrchestrationServiceReconfigureRequesterApproved
  fields:
  - to:
      value: "${/#miq_request.get_option(:owner_email)} || ${/#miq_request.requester.email}
        || ${/Configuration/Email/Default#default_recipient}"
  - subject:
      value: Request ID ${/#miq_request.id} - Your Service Reconfigure Request was
        Approved.
  - body:
      value: 'Hello,<br/><br/>Your Service Reconfigure Request was Approved.<br/><br/>To
        view this Request go to : <a href=${/#miq_request.show_url}>${/#miq_request.show_url}</a><br/><br/>
        Thank you,<br/> ${#signature}'
